// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyARNjY2yl7n6L6_d2aA5n2pSXHwkWCb-Yg',
    appId: '1:677882864073:android:3b3df4770065bcd4078818',
    messagingSenderId: '677882864073',
    projectId: 'seu-matrimony',
    storageBucket: 'seu-matrimony.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDVbMhgdhDy1z6EdSenRI_1xpNlVkaKkpc',
    appId: '1:677882864073:ios:41153bce8a70360b078818',
    messagingSenderId: '677882864073',
    projectId: 'seu-matrimony',
    storageBucket: 'seu-matrimony.firebasestorage.app',
    iosBundleId: 'com.example.seuMatrimony',
  );
}
