// Mocks generated by Mockito 5.4.6 from annotations
// in seu_matrimony/test/repositories/auth_repository_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i6;

import 'package:firebase_auth/firebase_auth.dart' as _i7;
import 'package:get/get.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:seu_matrimony/core/services/auth_service.dart' as _i3;
import 'package:seu_matrimony/core/services/mock_data_service.dart' as _i4;
import 'package:seu_matrimony/core/services/storage_service.dart' as _i5;
import 'package:seu_matrimony/data/models/user_model.dart' as _i8;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

class _FakeInternalFinalCallback_0<T> extends _i1.SmartFake
    implements _i2.InternalFinalCallback<T> {
  _FakeInternalFinalCallback_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeAuthResult_1 extends _i1.SmartFake implements _i3.AuthResult {
  _FakeAuthResult_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeMockAuthResult_2 extends _i1.SmartFake
    implements _i4.MockAuthResult {
  _FakeMockAuthResult_2(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [StorageService].
///
/// See the documentation for Mockito's code generation for more information.
class MockStorageService extends _i1.Mock implements _i5.StorageService {
  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get hasSeenOnboarding => (super.noSuchMethod(
        Invocation.getter(#hasSeenOnboarding),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  int get profileCompletion => (super.noSuchMethod(
        Invocation.getter(#profileCompletion),
        returnValue: 0,
        returnValueForMissingStub: 0,
      ) as int);

  @override
  bool get isProfileComplete => (super.noSuchMethod(
        Invocation.getter(#isProfileComplete),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  set accessToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #accessToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set refreshToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #refreshToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set firebaseToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #firebaseToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userId(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userId,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userEmail(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userEmail,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userName(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userName,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userRole(String? value) => super.noSuchMethod(
        Invocation.setter(
          #userRole,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isLoggedIn(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isLoggedIn,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set hasSeenOnboarding(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #hasSeenOnboarding,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set profileCompletion(int? value) => super.noSuchMethod(
        Invocation.setter(
          #profileCompletion,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set isProfileComplete(bool? value) => super.noSuchMethod(
        Invocation.setter(
          #isProfileComplete,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set userData(Map<String, dynamic>? value) => super.noSuchMethod(
        Invocation.setter(
          #userData,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  set fcmToken(String? value) => super.noSuchMethod(
        Invocation.setter(
          #fcmToken,
          value,
        ),
        returnValueForMissingStub: null,
      );

  @override
  T? read<T>(String? key) => (super.noSuchMethod(
        Invocation.method(
          #read,
          [key],
        ),
        returnValueForMissingStub: null,
      ) as T?);

  @override
  _i6.Future<void> write(
    String? key,
    dynamic value,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #write,
          [
            key,
            value,
          ],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> remove(String? key) => (super.noSuchMethod(
        Invocation.method(
          #remove,
          [key],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> clearAll() => (super.noSuchMethod(
        Invocation.method(
          #clearAll,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  bool hasKey(String? key) => (super.noSuchMethod(
        Invocation.method(
          #hasKey,
          [key],
        ),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<void> setUserId(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUserId,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserEmail(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUserEmail,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserName(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUserName,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> setUserRole(String? value) => (super.noSuchMethod(
        Invocation.method(
          #setUserRole,
          [value],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<void> saveUserData(String? jsonData) => (super.noSuchMethod(
        Invocation.method(
          #saveUserData,
          [jsonData],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<String?> getUserData() => (super.noSuchMethod(
        Invocation.method(
          #getUserData,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> clearAuthData() => (super.noSuchMethod(
        Invocation.method(
          #clearAuthData,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);
}

/// A class which mocks [AuthService].
///
/// See the documentation for Mockito's code generation for more information.
class MockAuthService extends _i1.Mock implements _i3.AuthService {
  @override
  bool get isLoggedIn => (super.noSuchMethod(
        Invocation.getter(#isLoggedIn),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Stream<_i7.User?> get authStateChanges => (super.noSuchMethod(
        Invocation.getter(#authStateChanges),
        returnValue: _i6.Stream<_i7.User?>.empty(),
        returnValueForMissingStub: _i6.Stream<_i7.User?>.empty(),
      ) as _i6.Stream<_i7.User?>);

  @override
  _i6.Stream<_i7.User?> get userChanges => (super.noSuchMethod(
        Invocation.getter(#userChanges),
        returnValue: _i6.Stream<_i7.User?>.empty(),
        returnValueForMissingStub: _i6.Stream<_i7.User?>.empty(),
      ) as _i6.Stream<_i7.User?>);

  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  _i6.Future<_i3.AuthResult> signUpWithEmail({
    required String? email,
    required String? password,
    required String? fullName,
    required String? phone,
    String? profileFor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signUpWithEmail,
          [],
          {
            #email: email,
            #password: password,
            #fullName: fullName,
            #phone: phone,
            #profileFor: profileFor,
          },
        ),
        returnValue: _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
              #profileFor: profileFor,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #signUpWithEmail,
            [],
            {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
              #profileFor: profileFor,
            },
          ),
        )),
      ) as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> signInWithEmail({
    required String? email,
    required String? password,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #signInWithEmail,
          [],
          {
            #email: email,
            #password: password,
          },
        ),
        returnValue: _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #signInWithEmail,
            [],
            {
              #email: email,
              #password: password,
            },
          ),
        )),
      ) as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<void> verifyPhoneNumber({
    required String? phoneNumber,
    required dynamic Function(_i7.PhoneAuthCredential)? onVerificationCompleted,
    required dynamic Function(String)? onVerificationFailed,
    required dynamic Function(
      String,
      int?,
    )? onCodeSent,
    required dynamic Function(String)? onCodeAutoRetrievalTimeout,
    int? forceResendingToken,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyPhoneNumber,
          [],
          {
            #phoneNumber: phoneNumber,
            #onVerificationCompleted: onVerificationCompleted,
            #onVerificationFailed: onVerificationFailed,
            #onCodeSent: onCodeSent,
            #onCodeAutoRetrievalTimeout: onCodeAutoRetrievalTimeout,
            #forceResendingToken: forceResendingToken,
          },
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<_i3.AuthResult> verifyOtpAndSignIn({
    required String? verificationId,
    required String? smsCode,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #verifyOtpAndSignIn,
          [],
          {
            #verificationId: verificationId,
            #smsCode: smsCode,
          },
        ),
        returnValue: _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #verifyOtpAndSignIn,
            [],
            {
              #verificationId: verificationId,
              #smsCode: smsCode,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #verifyOtpAndSignIn,
            [],
            {
              #verificationId: verificationId,
              #smsCode: smsCode,
            },
          ),
        )),
      ) as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> sendPasswordResetEmail(String? email) =>
      (super.noSuchMethod(
        Invocation.method(
          #sendPasswordResetEmail,
          [email],
        ),
        returnValue: _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #sendPasswordResetEmail,
            [email],
          ),
        )),
      ) as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> confirmPasswordReset({
    required String? code,
    required String? newPassword,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #confirmPasswordReset,
          [],
          {
            #code: code,
            #newPassword: newPassword,
          },
        ),
        returnValue: _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #confirmPasswordReset,
            [],
            {
              #code: code,
              #newPassword: newPassword,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #confirmPasswordReset,
            [],
            {
              #code: code,
              #newPassword: newPassword,
            },
          ),
        )),
      ) as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<_i3.AuthResult> sendEmailVerification() => (super.noSuchMethod(
        Invocation.method(
          #sendEmailVerification,
          [],
        ),
        returnValue: _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #sendEmailVerification,
            [],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i3.AuthResult>.value(_FakeAuthResult_1(
          this,
          Invocation.method(
            #sendEmailVerification,
            [],
          ),
        )),
      ) as _i6.Future<_i3.AuthResult>);

  @override
  _i6.Future<bool> isEmailVerified() => (super.noSuchMethod(
        Invocation.method(
          #isEmailVerified,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<Map<String, dynamic>?> getCurrentUserData() => (super.noSuchMethod(
        Invocation.method(
          #getCurrentUserData,
          [],
        ),
        returnValue: _i6.Future<Map<String, dynamic>?>.value(),
        returnValueForMissingStub: _i6.Future<Map<String, dynamic>?>.value(),
      ) as _i6.Future<Map<String, dynamic>?>);

  @override
  _i6.Stream<Map<String, dynamic>?> streamCurrentUserData() =>
      (super.noSuchMethod(
        Invocation.method(
          #streamCurrentUserData,
          [],
        ),
        returnValue: _i6.Stream<Map<String, dynamic>?>.empty(),
        returnValueForMissingStub: _i6.Stream<Map<String, dynamic>?>.empty(),
      ) as _i6.Stream<Map<String, dynamic>?>);

  @override
  _i6.Future<void> updateUserData(Map<String, dynamic>? data) =>
      (super.noSuchMethod(
        Invocation.method(
          #updateUserData,
          [data],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  _i6.Future<bool> isProfileComplete() => (super.noSuchMethod(
        Invocation.method(
          #isProfileComplete,
          [],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i6.Future<String?> getUserRole() => (super.noSuchMethod(
        Invocation.method(
          #getUserRole,
          [],
        ),
        returnValue: _i6.Future<String?>.value(),
        returnValueForMissingStub: _i6.Future<String?>.value(),
      ) as _i6.Future<String?>);

  @override
  _i6.Future<void> signOut() => (super.noSuchMethod(
        Invocation.method(
          #signOut,
          [],
        ),
        returnValue: _i6.Future<void>.value(),
        returnValueForMissingStub: _i6.Future<void>.value(),
      ) as _i6.Future<void>);

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}

/// A class which mocks [MockDataService].
///
/// See the documentation for Mockito's code generation for more information.
class MockMockDataService extends _i1.Mock implements _i4.MockDataService {
  @override
  _i2.InternalFinalCallback<void> get onStart => (super.noSuchMethod(
        Invocation.getter(#onStart),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onStart),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  _i2.InternalFinalCallback<void> get onDelete => (super.noSuchMethod(
        Invocation.getter(#onDelete),
        returnValue: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
        returnValueForMissingStub: _FakeInternalFinalCallback_0<void>(
          this,
          Invocation.getter(#onDelete),
        ),
      ) as _i2.InternalFinalCallback<void>);

  @override
  bool get initialized => (super.noSuchMethod(
        Invocation.getter(#initialized),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  bool get isClosed => (super.noSuchMethod(
        Invocation.getter(#isClosed),
        returnValue: false,
        returnValueForMissingStub: false,
      ) as bool);

  @override
  _i6.Future<_i4.MockAuthResult> login(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
        Invocation.method(
          #login,
          [
            email,
            password,
          ],
        ),
        returnValue: _i6.Future<_i4.MockAuthResult>.value(_FakeMockAuthResult_2(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.MockAuthResult>.value(_FakeMockAuthResult_2(
          this,
          Invocation.method(
            #login,
            [
              email,
              password,
            ],
          ),
        )),
      ) as _i6.Future<_i4.MockAuthResult>);

  @override
  _i6.Future<_i4.MockAuthResult> register({
    required String? email,
    required String? password,
    required String? fullName,
    required String? phone,
    required String? profileFor,
  }) =>
      (super.noSuchMethod(
        Invocation.method(
          #register,
          [],
          {
            #email: email,
            #password: password,
            #fullName: fullName,
            #phone: phone,
            #profileFor: profileFor,
          },
        ),
        returnValue: _i6.Future<_i4.MockAuthResult>.value(_FakeMockAuthResult_2(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
              #profileFor: profileFor,
            },
          ),
        )),
        returnValueForMissingStub:
            _i6.Future<_i4.MockAuthResult>.value(_FakeMockAuthResult_2(
          this,
          Invocation.method(
            #register,
            [],
            {
              #email: email,
              #password: password,
              #fullName: fullName,
              #phone: phone,
              #profileFor: profileFor,
            },
          ),
        )),
      ) as _i6.Future<_i4.MockAuthResult>);

  @override
  _i6.Future<bool> emailExists(String? email) => (super.noSuchMethod(
        Invocation.method(
          #emailExists,
          [email],
        ),
        returnValue: _i6.Future<bool>.value(false),
        returnValueForMissingStub: _i6.Future<bool>.value(false),
      ) as _i6.Future<bool>);

  @override
  _i8.UserModel? getUserByEmail(String? email) => (super.noSuchMethod(
        Invocation.method(
          #getUserByEmail,
          [email],
        ),
        returnValueForMissingStub: null,
      ) as _i8.UserModel?);

  @override
  void onInit() => super.noSuchMethod(
        Invocation.method(
          #onInit,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onReady() => super.noSuchMethod(
        Invocation.method(
          #onReady,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void onClose() => super.noSuchMethod(
        Invocation.method(
          #onClose,
          [],
        ),
        returnValueForMissingStub: null,
      );

  @override
  void $configureLifeCycle() => super.noSuchMethod(
        Invocation.method(
          #$configureLifeCycle,
          [],
        ),
        returnValueForMissingStub: null,
      );
}
